name: Dump ReX API
description: Dump ReX API for GDExtension

inputs:
  bin:
    description: The path to the ReX executable
    required: true

runs:
  using: composite
  steps:
    # Dump GDExtension interface and API
    - name: Dump GDExtension interface and API for redot-cpp build
      shell: sh
      run: |
        ${{ inputs.bin }} --headless --dump-gdextension-interface --dump-extension-api
        mkdir rex-api
        cp -f gdextension_interface.h rex-api/
        cp -f extension_api.json rex-api/

    - name: Upload API dump
      uses: ./.github/actions/upload-artifact
      with:
        name: redot-api-dump
        path: ./rex-api/*
