name: Build rex-cpp
description: Build rex-cpp with the provided options.

env:
  REX_CPP_BRANCH: 4.3

inputs:
  bin:
    description: Path to the ReX binary.
    required: true
    type: string
  scons-flags:
    description: Additional SCons flags.
    type: string
  scons-cache:
    description: The SCons cache path.
    default: ${{ github.workspace }}/.scons_cache/
    type: string

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        repository: Redot-Experimental/redot-cpp
        ref: ${{ env.REX_CPP_BRANCH }}
        path: rex-cpp

    - name: Extract API
      shell: sh
      run: ${{ inputs.bin }} --headless --dump-gdextension-interface --dump-extension-api

    - name: SCons Build
      shell: sh
      env:
        SCONS_CACHE: ${{ inputs.scons-cache }}
      run: scons --directory=./rex-cpp/test "gdextension_dir=${{ github.workspace }}" ${{ inputs.scons-flags }}
