#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

openssl_include_path = "/usr/include/openssl"  # Adjust based on your system

env.Append(CPPPATH=[openssl_include_path])
env.Append(LIBS=["ssl", "crypto"])
env.add_source_files(env.modules_sources, "*.cpp")  # Add all cpp files to the build
